coverage:
  status:
    project:
      default: off
      rust:
        target: 99%
        threshold: 0%
        flags:
          - rust
        if_not_found: failure
      javascript:
        target: 99%
        threshold: 0%
        flags:
          - javascript
        if_not_found: failure
    patch:
      default: off
      rust:
        target: 99%
        threshold: 0%
        flags:
          - rust
        if_not_found: failure
      javascript:
        target: 99%
        threshold: 0%
        flags:
          - javascript
        if_not_found: failure

flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: rust
    - name: javascript
